// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTv6BcONqMLpLa_HU-fBOHP0ytOW_jKY',
    appId: '1:584262741109:web:c24ff87576cd2ade4f9c3c',
    messagingSenderId: '584262741109',
    projectId: 'fifa-worldcup-2026-predictions',
    authDomain: 'fifa-worldcup-2026-predictions.firebaseapp.com',
    storageBucket: 'fifa-worldcup-2026-predictions.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXlCHBOwAiAPVaieqrqE6AJpSRCrLMb3w',
    appId: '1:584262741109:android:19640ae7fb9171944f9c3c',
    messagingSenderId: '584262741109',
    projectId: 'fifa-worldcup-2026-predictions',
    storageBucket: 'fifa-worldcup-2026-predictions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC63O-CrPoM3Zfe5ob8NVECsOuhfKOsJuI',
    appId: '1:584262741109:ios:561c4f08f27313614f9c3c',
    messagingSenderId: '584262741109',
    projectId: 'fifa-worldcup-2026-predictions',
    storageBucket: 'fifa-worldcup-2026-predictions.firebasestorage.app',
    iosBundleId: 'com.matan.worldcup.fifaWorldcup2026Predictions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC63O-CrPoM3Zfe5ob8NVECsOuhfKOsJuI',
    appId: '1:584262741109:ios:561c4f08f27313614f9c3c',
    messagingSenderId: '584262741109',
    projectId: 'fifa-worldcup-2026-predictions',
    storageBucket: 'fifa-worldcup-2026-predictions.firebasestorage.app',
    iosBundleId: 'com.matan.worldcup.fifaWorldcup2026Predictions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHTv6BcONqMLpLa_HU-fBOHP0ytOW_jKY',
    appId: '1:584262741109:web:97615959cbcb0bab4f9c3c',
    messagingSenderId: '584262741109',
    projectId: 'fifa-worldcup-2026-predictions',
    authDomain: 'fifa-worldcup-2026-predictions.firebaseapp.com',
    storageBucket: 'fifa-worldcup-2026-predictions.firebasestorage.app',
  );
}
